nodeLinker: node-modules

npmPublishRegistry: 'https://registry.npmjs.org/'

enableScripts: false

npmMinimalAgeGate: 7200
npmPreapprovedPackages:
  - '@avensia-oss/*'

yarnPath: .yarn/releases/yarn-4.10.3.cjs
